fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml ], fallback_format: json, prefer_extension: true }
            - { path: ^/, priorities: [ json, xml, html ], fallback_format: json, prefer_extension: true }
    body_converter:
        enabled: true
        validate: true
    view:
        view_response_listener: true
        formats:
            json: true
            xml:  true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    disable_csrf_role: ROLE_API
    serializer:
        serialize_null: true
