# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    logout_listener:
        class: VPNAdmin\ApiBundle\Controller\LogoutListener

imports:
    - { resource: "@VPNAdminApiBundle/Resources/config/services.yml" }
